apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-deployment
  labels:
    app: watch
spec:
  template:
    metadata:
      labels:
        app: watch
    spec:
      containers:
        - name: watch-container
          image: bsbiradar/my-watch-ingress:v1
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: watch
  strategy:
    type: RollingUpdate