apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biradar-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
  - hosts:
      - biradar.shop
      - grocery.biradar.shop
      - watch.biradar.shop
    secretName: tls-secret
  rules:
  - host: "grocery.biradar.shop"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: shop-svc
            port:
              number: 80
  - host: "watch.biradar.shop"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: watch-svc
            port:
              number: 80